import { Roboto } from "next/font/google";
import "./globals.css";
import MyThemeProvider from "@/theme";
// import { CssBaseline } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Helvetica", "Arial", "sans-serif"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MyThemeProvider>
        <body className={roboto.className}>{children}</body>
      </MyThemeProvider>
    </html>
  );
}
